name: streamed_controller
description: A predictable state management library with prebuilt concurrency helpers that implement the Business Logic Component design pattern without complexity of BLoC.
version: 0.3.0
repository: https://github.com/hot-moms/streamed_controller
issue_tracker: https://github.com/hot-moms/streamed_controller/issues
homepage: https://github.com/hot-moms/streamed_controller

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
